name: Deploy Astro site to GitHub Pages

on:
  push:
    branches:
      - main  # Change this if your default branch is not 'main'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4  # Updated to use Node.js 20
  
      - name: Setup Node.js
        uses: actions/setup-node@v4  # Updated to use Node.js 20
        with:
          node-version: '20'  # Updated to Node.js 20
  
      - name: Install dependencies
        run: npm ci
  
      - name: Build the site
        run: npm run build
  
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4  # Updated to use Node.js 20
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist  # Adjust this if your build output directory is different